#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

checkexchangerate:
    path: /api/check-exchange-rate
    controller: App\Controller\DefaultController::checkExchangeRate
    methods: GET

check_exchange_rate_history:
    path: /api/check-exchange-rate/{currency}/{days}
    controller: App\Controller\DefaultController::chechExchangeRateHistory
    methods: GET
index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*
    # controller: App\Controller\DefaultController::index

